services:
  client:
    build:
      context: ./client/
      dockerfile: ${DOCKERFILE}  
    ports:
      - "3000:3000"  # 80
    volumes:
      - ./client:/client # mount hele lortet
    environment:
      - CHOKIDAR_USEPOLLING=true 
      - WATCHPACK_POLLING=true 
      - FAST_REFRESH=false
      - WDS_SOCKET_PORT=3000 #something hto reload

  server:
    build:
      context: ./server/
      dockerfile: ${DOCKERFILE}
    ports: 
      - "4000:4000"
    env_file:
      - .env