services:
  client:
    build:
      context: ./client/
      dockerfile: ${DOCKERFILE}  
    ports:
      - "5173:5173"  
    volumes:
      - ./client:/client 

  server:
    build:
      context: ./server/
      dockerfile: ${DOCKERFILE}
    ports: 
      - "4000:4000"
    env_file:
      - .env


      